# Generated by Django 2.2.10 on 2020-05-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefile', '0003_auto_20200531_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
